Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [1]:
import numpy as np

a = [[1], [2], [3], [3], [1]]
b = [[6], [8], [11], [10], [7]]
mean_a = np.zeros(2,)
a = np.column_stack((a,b))
mean_a = np.zeros(2,)
print(a)
np.mean(a, axis = 0,out = mean_a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


array([2. , 8.4])

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [2]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [4]:
[v1,v2] = np.hsplit(a_centered, 2)
v1 = np.reshape(v1,(1,5))
a_centered_sp = v1.dot(v2)
sh = a.shape[0]
a_centered_sp / (sh-1)

array([[2.]])

Задание 4

In [6]:
a_t = np.transpose(a)
m = np.cov(a_t)
m

array([[1. , 2. ],
       [2. , 4.3]])

### Работа с данными в Pandas

Задание 1

In [8]:
import pandas as pd

authors = {"author_id" : [1, 2, 3],
          "author_name" : ['Тургенев', 'Чехов', 'Островский'] }
authors = pd.DataFrame(authors)
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [9]:
book = {'author_id': [1, 1, 1, 2, 2, 3, 3],
       'book_title' : ['Отцы и дети', 'Рудин', 
                       'Дворянское гнездо', 'Толстый и тонкий',
                       'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
       'price' : [450, 300, 350, 500, 450, 370, 290]}
book = pd.DataFrame(book)
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

Задание 2

In [10]:
author_price = pd.merge(authors, book, how ='inner', on = 'author_id')
author_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

Задание 3

In [11]:
top5 = pd.merge(authors, book, how ='inner', on = 'author_id')

top_all = top5.sort_values(by=['price'], ascending=False) #для дальнейшей сортировки

top5 = top5.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

Задание 4

In [12]:
author_stat = top_all.groupby('author_name').agg(
    price_min = pd.NamedAgg(column = 'price', aggfunc = 'min'),
    price_max = pd.NamedAgg(column = 'price', aggfunc = 'max'),
    price_mean = pd.NamedAgg(column = 'price', aggfunc = 'mean')
    )
author_stat

price_min  price_max  price_mean
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000